run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - performance
      - style
    disabled-checks:
      - dupImport
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
      - name: error-return
        severity: warning
      - name: error-naming
        severity: warning
      - name: var-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: unexported-naming
        severity: warning
      - name: time-naming
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: context-as-argument
        severity: warning

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - revive
    - gocritic
    - gocyclo
    - misspell
    - unconvert
    - unparam
    - prealloc
    - exportloopref
    - gosec
    - errname
    - errorlint
    - gochecknoglobals
    - gochecknoinits
    - gofumpt
  disable:
    - deadcode
    - varcheck
    - structcheck
    - maligned
    - interfacer
    - scopelint
    - golint

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - goconst
    - path: cmd/
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

